# Generated by Django 4.2.6 on 2023-10-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='image_post'),
        ),
    ]
